<a href="https://colab.research.google.com/github/ayalarodrigues/residencia-ciberseguranca/blob/main/ETL_parte_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd

Lê o arquivo CSV e transforma os dados em um DataFrame

In [17]:
df = pd.read_csv("vendas_loja.csv")

# Exercício 1: Leitura e inspeção inicial

Escreva um código para:

- ler o arquivo vendas_loja.csv;

- exibir as 5 primeiras linhas;

- mostrar a quantidade de linhas e colunas da base;

- listar os nomes das colunas.

In [25]:
print("5 primeiras linhas:")
print(df.head())
print("\nQuantidade de linhas e colunas da base:")
print(df.shape)
print("\nNomes das colunas:")
print(df.columns)

5 primeiras linhas:
   id_venda        data            produto    categoria    preco  quantidade  \
0         1  2025-01-13         Monitor 24  Eletrônicos  1165.97           4
1         2  2025-12-13         Monitor 24  Eletrônicos  1165.38           2
2         3  2025-01-17             Tablet  Eletrônicos   779.31           4
3         4  2025-01-14    Livro de Python       Livros   131.17           7
4         5  2025-10-29  Mochila Executiva   Acessórios   192.33           3

      cidade vendedor
0      Natal    Carla
1   São Luís     João
2      Natal  Isabela
3   São Luís   Daniel
4  Fortaleza    Lucas

Quantidade de linhas e colunas da base:
(6000, 8)

Nomes das colunas:
Index(['id_venda', 'data', 'produto', 'categoria', 'preco', 'quantidade',
       'cidade', 'vendedor'],
      dtype='object')

# Exercício 2: Conhecendo a estrutura do DataFrame

Depois de carregar a base em um DataFrame chamado df, responda com comandos em Python:

- qual comando mostra informações sobre tipos de dados e valores não nulos;
- qual comando exibe um resumo estatístico das colunas numéricas;
- qual comando mostra 8 linhas aleatórias da base.

In [26]:
print("Tipos de dados e valores não nulos:")
df.info()
print("\nResumo estatístico das colunas numéricas:")
print(df.describe())
print("\n8 linhas aleatórias da base:")
df.sample(8)

Tipos de dados e valores não nulos:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_venda    6000 non-null   int64
 1   data        6000 non-null   object
 2   produto     6000 non-null   object
 3   categoria   6000 non-null   object
 4   preco       6000 non-null   float64
 5   quantidade  6000 non-null   int64
 6   cidade      6000 non-null   object
 7   vendedor    6000 non-null   object
dtypes: float64(1), int64(2), object(5)
memory usage: 375.1+ KB

Resumo estatístico das colunas numéricas:
          id_venda        preco   quantidade
count  6000.000000  6000.000000  6000.000000
mean   3000.500000   766.195737     4.532000
std    1732.195139   991.092340     2.303518
min       1.000000    35.500000     1.000000
25%    1500.750000   150.342500     3.000000
50%    3000.500000   363.445000     5.000000
75%    4500.250000   976.682500     7.000000
max    6000.000000  4963.640000     8.000000

8 linhas aleatórias da base:

,id_venda,data,produto,categoria,preco,quantidade,cidade,vendedor
2804,2805,2025-02-21,Webcam,Eletrônicos,145.73,2,Belém,Ana
892,893,2025-10-09,Mouse,Informática,103.69,8,João Pessoa,Karina
1232,1233,2025-03-01,Garrafa Térmica,Acessórios,72.20,5,Teresina,Karina
4469,4470,2025-07-11,Teclado,Informática,226.02,4,João Pessoa,Carla
1531,1532,2025-06-19,Headset,Informática,319.80,7,Belém,Gabriela
5470,5471,2025-04-21,Mochila Executiva,Acessórios,384.80,7,João Pessoa,Lucas
3396,3397,2025-01-28,Webcam,Eletrônicos,250.75,5,Teresina,Lucas
1524,1525,2025-08-30,Notebook,Eletrônicos,4331.48,7,Salvador,Daniel

# Exercício 3: Seleção de colunas

Escreva um código para:

- selecionar apenas as colunas produto, categoria, preco e quantidade;
- salvar esse subconjunto em uma variável chamada vendas_resumo;
- exibir as 10 primeiras linhas do resultado.

In [27]:
vendas_resumo = df[["produto", "categoria", "preco", "quantidade"]]
vendas_resumo.head(10)

             produto    categoria    preco  quantidade
0         Monitor 24  Eletrônicos  1165.97           4
1         Monitor 24  Eletrônicos  1165.38           2
2             Tablet  Eletrônicos   779.31           4
3    Livro de Python       Livros   131.17           7
4  Mochila Executiva   Acessórios   192.33           3
5             Tablet  Eletrônicos  1264.79           6
6            Teclado  Informática    99.34           5
7  Mochila Executiva   Acessórios   153.98           2
8         HD Externo  Informática   539.78           4
9            Teclado  Informática   220.74           2

# Exercício 4: Filtragem simples por cidade

Crie um filtro para mostrar apenas as vendas realizadas na cidade de Fortaleza.

Em seguida, mostre quantos registros existem nesse subconjunto.

In [34]:
vendas_fortaleza = df[df["cidade"] == "Fortaleza"] #para cada linha, verifica se a coluna cidade é igual a 'Fortaleza'
vendas_fortaleza

,id_venda,data,produto,categoria,preco,quantidade,cidade,vendedor
4,5,2025-10-29,Mochila Executiva,Acessórios,192.33,3,Fortaleza,Lucas
13,14,2025-01-29,Webcam,Eletrônicos,189.55,6,Fortaleza,Gabriela
18,19,2025-09-18,Headset,Informática,282.86,2,Fortaleza,Carla
22,23,2025-08-11,HD Externo,Informática,346.43,5,Fortaleza,Isabela
32,33,2025-01-04,Impressora,Eletrônicos,624.54,4,Fortaleza,Bruno
...,...,...,...,...,...,...,...,...
5905,5906,2025-08-15,Caixa de Som,Eletrônicos,163.48,1,Fortaleza,Henrique
5917,5918,2025-04-15,Mouse,Informática,123.02,5,Fortaleza,Daniel
5951,5952,2025-09-23,Filtro de Linha,Casa,67.31,8,Fortaleza,Daniel
5982,5983,2025-01-06,Luminária LED,Casa,72.48,2,Fortaleza,Carla
5998,5999,2025-01-17,Headset,Informática,334.39,7,Fortaleza,João

In [33]:
print("Quantidade de registro de vendas em Fortaleza:", len(vendas_fortaleza))

Quantidade de registro de vendas em Fortaleza: 572

# Exercício 5: Filtragem composta

Escreva um código para filtrar somente os registros em que:

- categoria seja igual a Informática;
- e quantidade seja maior ou igual a 5.

In [35]:
categoria_informatica = df[(df["categoria"] == "Informática") & (df["quantidade"] >= 5)]
categoria_informatica

,id_venda,data,produto,categoria,preco,quantidade,cidade,vendedor
6,7,2025-07-14,Teclado,Informática,99.34,5,Maceió,Ana
14,15,2025-02-03,SSD 1TB,Informática,347.77,6,Belém,Daniel
16,17,2025-05-07,Headset,Informática,376.82,5,São Luís,Lucas
22,23,2025-08-11,HD Externo,Informática,346.43,5,Fortaleza,Isabela
33,34,2025-06-19,Mouse,Informática,54.01,5,Natal,Karina
...,...,...,...,...,...,...,...,...
5976,5977,2025-05-02,Mouse,Informática,122.55,6,Aracaju,Felipe
5992,5993,2025-02-08,Headset,Informática,386.46,6,João Pessoa,Carla
5994,5995,2025-04-20,Mouse,Informática,96.14,8,Recife,Henrique
5997,5998,2025-12-20,Teclado,Informática,268.90,7,Salvador,Lucas
5998,5999,2025-01-17,Headset,Informática,334.39,7,Fortaleza,João

In [36]:
print("Quantidade de linha:", len(categoria_informatica))

Quantidade de linha: 737

# Exercício 6: Filtro com preço e múltiplas cidades

Escreva um código para selecionar as vendas com preço acima de 1000 que tenham ocorrido em Recife ou Salvador.

Mostre as 10 primeiras linhas do resultado e informe a quantidade de registros encontrados.

In [37]:
filtro_cidades_preco = df[(df["preco"] > 1000) & (df["cidade"] == "Recife") | (df["cidade"] == "Salvador")]
filtro_cidades_preco.head(10)

,id_venda,data,produto,categoria,preco,quantidade,cidade,vendedor
37,38,2025-06-23,Smartphone,Eletrônicos,3011.36,4,Recife,Daniel
52,53,2025-04-20,Filtro de Linha,Casa,74.40,6,Salvador,Bruno
60,61,2025-02-27,Notebook,Eletrônicos,3386.80,1,Salvador,Felipe
61,62,2025-10-10,Cafeteira,Casa,254.60,1,Salvador,Eduarda
68,69,2025-07-24,Mesa Escritório,Móveis,1003.85,5,Recife,Felipe
92,93,2025-04-29,Headset,Informática,251.33,4,Salvador,Bruno
98,99,2025-03-26,Smartphone,Eletrônicos,3147.02,1,Salvador,Gabriela
127,128,2025-01-28,Mouse,Informática,105.16,8,Salvador,Bruno
135,136,2025-05-16,Mesa Escritório,Móveis,1420.36,4,Salvador,Carla
147,148,2025-11-22,Tablet,Eletrônicos,2269.54,8,Recife,Felipe

In [39]:
print("Quantidade de registros encontrados:", len(filtro_cidades_preco))

Quantidade de registros encontrados: 784

# Exercício 7: Resumo rápido da base

Usando a base completa, descubra:

- o preço médio da coluna preco;
- a soma total da coluna quantidade;
- a quantidade de vendedores distintos presentes na base.

In [40]:
preco_medio = df["preco"].mean() #men retorna o valor da média aritmética de uma coluna
soma_quantidade = df["quantidade"].sum() #soma todos os valores de uma coluna
quantidade_vendedores_distintos = df["vendedor"].nunique() #conta quantos valores diferentes existem na coluna

In [42]:
print("Preço médio da coluna preço:", preco_medio)
print("Soma total da coluna quantidade:", soma_quantidade)
print("Quantidade de vendedores distintos presentes na base:", quantidade_vendedores_distintos)

Preço médio da coluna preço: 766.1957366666667
Soma total da coluna quantidade: 27192
Quantidade de vendedores distintos presentes na base: 12

# Exercício 8: Exploração orientada com base maior

- Identifique os 5 produtos com maior número de registros na base.
- Apresente o resultado ordenado do maior para o menor.

In [43]:
mais_registrados = df["produto"].value_counts().head(5) #value_counts já ordena do maior para o menor
mais_registrados

produto
Filtro de Linha    340
Headset            338
HD Externo         331
Monitor 24         316
Smartphone         309
Name: count, dtype: int64

In [44]:
print(mais_registrados)

produto
Filtro de Linha    340
Headset            338
HD Externo         331
Monitor 24         316
Smartphone         309
Name: count, dtype: int64

# Exercício 9: Relação com ETL

Explique, com suas palavras, como as operações abaixo se relacionam com o processo ETL:
- ler o CSV com pd.read_csv();
  
   **Ler o CSV com pd.read_csv() corresponde à etapa de extração, já que estamos organizando a base de dados e mantendo apenas o que é de interesse para a análise.**

- selecionar apenas algumas colunas;

  **Selecionar apenas algumas colunas corresponde à etapa de transformação, pois estamos fazendo um refinamento dos dados e deixando apenas o que é desejado.**

- filtrar registros de uma cidade específica;

  **Filtrar registros de uma cidade específica corresponde também à etapa de transformação, pois ainda estamos refinando os dados e deixando apenas o que desejamos.**

- salvar um novo arquivo com a base tratada.

  **Salvar um novo arquivo com a base tratada corresponde à etapa de carregamento, já que os dados que foram trasnformados serão gravados em algum lugar para serem usados.**

# Exercício 10: Mini pipeline prático

Monte um pequeno roteiro em Python que faça o seguinte:

- leia a base vendas_loja.csv;
- selecione apenas as colunas produto, preco, quantidade e cidade;
- filtre registros com preco maior ou igual a 100;
- filtre apenas registros da cidade de Fortaleza;
- exiba as 10 primeiras linhas do resultado final;
- salve o resultado em um arquivo chamado fortaleza_filtrado.csv.

In [56]:
import pandas as pd

df = pd.read_csv("vendas_loja.csv")

# Seleciona apenas as colunas pedidas
df_pipeline = df[["produto", "preco", "quantidade", "cidade"]]

# Filtra apenas preços maiores ou iguais a 100
df_pipeline = df_pipeline[df_pipeline["preco"] >= 100]

# Filtra apenas a cidade de Fortaleza
df_pipeline = df_pipeline[df_pipeline["cidade"] == "Fortaleza"]

# Mostra as 10 primeiras linhas do resultado final
print(df_pipeline.head(10))

# Salva em um novo arquivo CSV
df_pipeline.to_csv("fortaleza_filtrado.csv", index=False)

              produto    preco  quantidade     cidade
4   Mochila Executiva   192.33           3  Fortaleza
13             Webcam   189.55           6  Fortaleza
18            Headset   282.86           2  Fortaleza
22         HD Externo   346.43           5  Fortaleza
32         Impressora   624.54           4  Fortaleza
36             Tablet  1587.35           2  Fortaleza
44    Mesa Escritório   861.24           1  Fortaleza
57            SSD 1TB   445.41           2  Fortaleza
64     Cadeira Office  1111.06           3  Fortaleza
84         Impressora  1238.86           2  Fortaleza

# Exercício 11: Desafio adicional

Crie um filtro para selecionar apenas vendas da categoria Informática na cidade de Fortaleza.

Depois, calcule a quantidade de linhas desse subconjunto e o preço médio encontrado.

In [55]:
informatica_fortaleza = df[(df["categoria"] == "Informática") & (df["cidade"] == "Fortaleza")]
quantidade_linhas = len(informatica_fortaleza)
preco_medio_info_fortal = informatica_fortaleza["preco"].mean()

print("Quantidade de linhas do filtro:", quantidade_linhas)
print("Preço médio do filtro:", preco_medio_info_fortal)

Quantidade de linhas do filtro: 146
Preço médio do filtro: 309.80171232876717